a = input('Digite algo: ')
print('Tipo: ',type(a))
print('Numérico: ',a.isnumeric())
print('Alfa Numérico: ',a.isalnum())
print('Alfabético: ',a.isalpha())
print('Minúsculas: ',a.islower())
print('Maiúscula: ',a.isupper())
print('Decimal: ',a.isdecimal())
print('Espaço: ',a.isspace())
print('Título: ',a.istitle())
print('Imprimível: ',a.isprintable())